version: '3'

services:
  sensor1:
    image: youla_dev_internship_task_go_sensor:latest
    container_name: sensor1
    ports:
      - "8081:8080"
  sensor2:
    image: youla_dev_internship_task_go_sensor:latest
    container_name: sensor2
    ports:
      - "8082:8080"
  sensor3:
    image: youla_dev_internship_task_go_sensor:latest
    container_name: sensor3
    ports:
      - "8083:8080"
  sensor4:
    image: youla_dev_internship_task_go_sensor:latest
    container_name: sensor4
    ports:
      - "8084:8080"
