version: '3'

services:
  sensor1:
    image: youla_dev_internship_task_go_sensor:latest
    container_name: sensor1
  sensor2:
    image: youla_dev_internship_task_go_sensor:latest
    container_name: sensor2
  sensor3:
    image: youla_dev_internship_task_go_sensor:latest
    container_name: sensor3
  sensor4:
    image: youla_dev_internship_task_go_sensor:latest
    container_name: sensor4
  aggreg:
    image: internship_task_go_aggreg:latest
    container_name: aggreg
    ports:
    - 8080:8080
    depends_on:
    - sensor1
    - sensor2
    - sensor3
    - sensor4
    volumes:
    - ./config.json:/config.json:ro
